pipeline:
  identifier: Build_credzy_1696283592861
  name: Build credzy
  orgIdentifier: default
  projectIdentifier: TEST
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1695829315182
        repoName: credzy
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
